### ISSUE TITLE
Gravity 'Script Location' link broken

### ISSUE THREAD

**Issue by crsmi** [pi-hole/docs#169]
`/doc/core/pihole-command.md` has a link under Gravity > Script Location labelled "/opt/pihole/gravity.sh" which has an incorrect URL.

The URL is:

"https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/gravity.sh"
 
but should be:

"https://github.com/pi-hole/pi-hole/blob/master/gravity.sh"

**Comment by dschaper** [comment]
Thanks for the issue. Do you want to PR a fix for that?

**Comment by crsmi** [comment]
Sure! Should I just PR submit to `master`? I think the typo also exists in the `gh-pages` branch, but I'm not sure what the plan for that branch is.

Also, I ran a link checker and found two other broken links. Can I include fixes for these in the same PR?
