### ISSUE TITLE
Errors and omissions in the OpenVPN pihole guide 

### ISSUE THREAD

**Issue by HarvsG** [pi-hole/docs#24]
Is it me or had this guide only just moved to https://docs.pi-hole.net/guides/vpn, I swear I was using it last week in a github wiki format, or was that a rehost?

I've noticed a few things.

1. In the firewall config guide,  the bit on dropping https connections for improved speed isn't there (it was on the previous guide I used)
2. In the firewall section there is nothing about how to save the firewall config and load it at startup (I think there was in the previous guide)
3. In the [VPN + Lan config section](https://docs.pi-hole.net/guides/vpn/dual-operation/) there is an inappropriate html tag in one of the code blocks `push "dhcp-option DNS <b>192.168.2.123</b>"`

**Comment by HarvsG** [comment]
During the DNS over HTTPS tutorial the [Docs](https://docs.pi-hole.net/guides/dns-over-https/#configuring-pi-hole) suggest entering in the local DNS server `127.0.0.1#5053` in the GUI the formatted custom DNS box does not allow the entering of `#` or sections of more than 3 digits

**Comment by PromoFaux** [comment]
Yeah, you'll need to be on Pi-hole 4.0 (Currently `FTLDNS` beta) As stated on the front page of the docs site:
https://docs.pi-hole.net/

**Comment by HarvsG** [comment]
Ahh, I didn't realise that was for all tutorials, I edited the /etc/pihole/setupVars.conf manually and that worked. How stable is Pi-Hole 4.0? Is it worth switching?

**Comment by PromoFaux** [comment]
Feeling pretty confident with it right now, but there are possible still a couple of things we haven't caught... there always are! But I've been running it with no issues personally. YMMV :)

**Comment by Mcat12** [comment]
Number 1 has been fixed: https://docs.pi-hole.net/guides/vpn/firewall/#blocking-https-advertisement-assets
Number 2 has been fixed: https://docs.pi-hole.net/guides/vpn/firewall/#save-your-iptables
Number 3 was previously fixed.
