### ISSUE TITLE
Unbound private-address seems to cause querry issues

### ISSUE THREAD

**Issue by hduelme** [pi-hole/docs#360]
### Versions
unbound 1.9.0

### Platform
Rasberry Pi 3B+

### Expected behaviour
Answer the DNS queries with an IP-address.
 

### Actual behaviour / bug
I had problems with some DNS queries. After reducing the private-address to my local address range the problems were gone.
The IP-addresses with problems are in the range 172.30 to 172.31. It seems like the default private range was from 169.254 to 192.168.

### Steps to fix
Reducing the private-address to your local used ranges.

### Screenshots
Answer with default private-address:
![Bildschirmfoto vom 2020-08-15 12-10-36](https://user-images.githubusercontent.com/46139144/90310272-5a7ed400-def0-11ea-9667-56e146e1e12e.png)

Answer after reducing to my locale private-address (192.168.2.0 to 192.168.2.2):
![Bildschirmfoto vom 2020-08-15 11-57-20](https://user-images.githubusercontent.com/46139144/90310248-3c18d880-def0-11ea-99d3-ce72feb5e93e.png)

**Comment by dschaper** [comment]
172.30 to 172.31 are private prefixes (RFC 1918) and are not routeable on the Internet. 

What was the intent of making the changes? The default `private-range` entries cover all the RFC 1918 space along with the other IP address space used for LAN only needs.

**Comment by hduelme** [comment]
You are right.  It was an VPN problem.
Thx
