### ISSUE TITLE
group Table Schema in database doesn't match documentation. Not sure which one should be corrected?

### ISSUE THREAD

**Issue by mwoolweaver** [pi-hole/docs#415]
### Versions

  Pi-hole version is v5.1.2 (Latest: v5.1.2)
  AdminLTE version is v5.1.1 (Latest: v5.1.1)
  FTL version is v5.2 (Latest: v5.2)

### Platform

- OS and version:  Linux Mint 20 Ulyana

- Platform:  iMac

### Expected behavior

info to match.

### Actual behavior / bug

documentation say NOT unique --> https://docs.pi-hole.net/database/gravity/groups/

Label | Type | Uniqueness enforced | Content
----- | ---- | ------------------- | --------
`id` | integer | Yes | Unique ID for database operations
`enabled` | boolean | No | Flag whether domains in this group should be used<br>(`0` = disabled, `1` = enabled)
`name` | text | No | Mandatory group name
`description` | text | No | Optional field for arbitrary user comments

`group` Table Schema says `UNIQUE`

```
CREATE TABLE "group"
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	enabled BOOLEAN NOT NULL DEFAULT 1,
	name TEXT UNIQUE NOT NULL,
	date_added INTEGER NOT NULL DEFAULT (cast(strftime('%s', 'now') as int)),
	date_modified INTEGER NOT NULL DEFAULT (cast(strftime('%s', 'now') as int)),
	description TEXT
)
```

### Steps to reproduce

1. go to --> https://docs.pi-hole.net/database/gravity/groups/
2. check first Table on page.
3. See 
     >Label | Type | Uniqueness enforced | Content
     >----- | ---- | ------------------- | --------
     >`name` | text | No | Mandatory group name

4. open `/etc/pihole/gravity.db` in [DB Browser](https://sqlitebrowser.org) 
5. check `group` Table Schema
6. see included pic

## Debug Token

- URL:  https://tricorder.pi-hole.net/z5sfkyhqsw

### Screenshots

![pi-hole-database](https://user-images.githubusercontent.com/5729320/98082262-0d9b0180-1e3e-11eb-88c1-3ff1139c6f20.png)

**Comment by DL6ER** [comment]
Yes, this is incorrect in the documentation, it should be

Label | Type | Uniqueness enforced | Content
----- | ---- | ------------------- | --------
`id` | integer | Yes | Unique ID for database operations
`enabled` | boolean | No | Flag whether domains in this group should be used<br>(`0` = disabled, `1` = enabled)
`name` | text | **Yes** | Mandatory group name
`description` | text | No | Optional field for arbitrary user comments

**Comment by mwoolweaver** [comment]
That's what I was thinking.
