### ISSUE TITLE
Broken links when opening VPN overview from https://pi-hole.net/

### ISSUE THREAD

**Issue by deosrc** [pi-hole/docs#428]
### Versions

N/A

### Platform

N/A

### Expected behavior

After navigating to the VPN docs from https://pi-hole.net/, clicking navigation links works.

### Actual behavior / bug

After following the link from https://pi-hole.net/ to https://docs.pi-hole.net/guides/vpn/overview , all of the links for the VPN section are broken.

Adding a trailing slash to the url (e.g. `https://docs.pi-hole.net/guides/vpn/overview/` fixes the links.

### Steps to reproduce

1. Go to https://pi-hole.net/
2. Click on the "PI-HOLE + VPN" button in section 4.
3. Click on any of the navigation links under "Pi-Hole and OpenVPN Server"

## Debug Token

N/A

### Screenshot

None

### Additional context

None

**Comment by dschaper** [comment]
Which browser are you using? I've just tried with FireFox and the existing URL loads without any issue for me.

**Comment by dschaper** [comment]
Ah, check that, I didn't get to step 3.

**Comment by dschaper** [comment]
Fixed on Wordpress. Dumped the cache so it should show up in a short while.
