### ISSUE TITLE
Unbound documentation error

### ISSUE THREAD

**Issue by dmginc** [pi-hole/docs#433]
In the section that talks about the /etc/unbound/unbound.conf.d/pi-hole.conf file, it shows:

```
    # Use this only when you downloaded the list of primary root servers!
    # If you use the default dns-root-data package, unbound will find it automatically
    #root-hints: "/var/lib/unbound/root.hints"
```
Why is this commented out when the step right before generating this config file is to manually download the root.hints file?

**Comment by dschaper** [comment]
Read the first line.

**Comment by dmginc** [comment]
I did, that's why I posted this question :P  Since the documentation has you run the following in the step prior.

```
wget https://www.internic.net/domain/named.root -qO- | sudo tee /var/lib/unbound/root.hints
```

**Comment by dschaper** [comment]
Then uncomment the line.

Copy/pasting config files without reading and understanding them will cause a whole host of bad times.

**Comment by dmginc** [comment]
Oh, though I guess that step is "Optional". So disregard.

**Comment by dmginc** [comment]
> Then uncomment the line.
> 
> Copy/pasting config files without reading and understanding them will cause a whole host of bad times.

Well yeah, I just didn't realize the step was optional.  Otherwise it was unnecessarily commented out.
