### ISSUE TITLE
Internal links not working without forward-slash in URL

### ISSUE THREAD

**Issue by rosscg** [pi-hole/docs#440]
### Platform

Tested on Safari and Chrome on Mac OSX

### Expected behavior

Navigate to https://docs.pi-hole.net/guides/vpn/overview
Click any link to another docs page 
View page

### Actual behavior / bug

Navigate to https://docs.pi-hole.net/guides/vpn/overview
Click any link to another docs page 
**receive 404 error**

### Steps to reproduce

Use, for example:
https://docs.pi-hole.net/guides/vpn/overview
Instead of:
https://docs.pi-hole.net/guides/vpn/overview/
(ie. omit final forward-slash)
Click link at the end of first paragraph: "this section of the tutorial"

### Additional context

Relevant as the failing URL is linked from external pages, for example:
https://makezine.com/projects/raspberry-pi-network-ad-blocker/

**Comment by PromoFaux** [comment]
Ah-hah! I guess this is what you were trying to fix with #425 ?

**Comment by rosscg** [comment]
You got it ! Stumbled across the problematic page again so made sure to document it for you.

**Comment by XhmikosR** [comment]
If it's not https://github.com/datarobot/mkdocs-redirects to blame, it could be mkdocs (which I doubt though) or Netlify.

**Comment by PromoFaux** [comment]
Fixed by enabling `Pretty URLs` in the site settings. "Asset optimization" was disabled entirely, so have left the other rules as they were

![image](https://user-images.githubusercontent.com/1998970/125193190-16e93300-e243-11eb-8be4-eb76b1b4185b.png)

**Comment by XhmikosR** [comment]
@PromoFaux the images setting is moot being that there's a GitHub Action here already which takes care of it.
