### ISSUE TITLE
Documentation:

### ISSUE THREAD

**Issue by salamdamai** [pi-hole/docs#452]
Not so much on the code. I am newly installing pihole in a cloud machine along with openvpn. The documentation that talks about firewall setting: 

https://docs.pi-hole.net/guides/vpn/firewall/

is very misleading. Let say if I follow "Option 2: Explicitly allow what can be accessed within the VPN", you will notice that somewhere down, the documentation indicate to execute "iptables -P INPUT DROP"

That executing locks me out of the node. Luckily I figured out on how to launch a web-based terminal from the cloud website. I have deleting/creating nodes over and over until I finally figured out the iptables command the lock me out. On top of that, I still could not use pihole through VPN tunner. So i truly need the proper firewall setup to make this to work. 

Thank you guys for the hardwork.

**Comment by dschaper** [comment]
The documentation is correct.

You open the specific ports you need ( like web, ssh, dns) and then drop everything else. At that point you can only access via the VPN.

**Comment by salamdamai** [comment]
This is the output of "iptables -L --line-number" after executing "iptables -P INPUT DROP" 

root@li334-231:~# iptables -L --line-numbers
Chain INPUT (policy DROP)
num  target     prot opt source               destination         
1    ACCEPT     all  --  anywhere             anywhere            
2    ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
3    ACCEPT     udp  --  anywhere             anywhere             udp dpt:openvpn
4    ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:openvpn
5    ACCEPT     udp  --  anywhere             anywhere             udp dpt:openvpn

Chain FORWARD (policy ACCEPT)
num  target     prot opt source               destination         
1    ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
2    ACCEPT     all  --  10.8.0.0/24          anywhere            

Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

Why would I want the openvpn connection INPUT to be drop?

**Comment by salamdamai** [comment]
This is the output if I set it to ACCEPT.

root@li334-231:~# iptables -L --line-numbers
Chain INPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    ACCEPT     all  --  anywhere             anywhere            
2    ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
3    ACCEPT     udp  --  anywhere             anywhere             udp dpt:openvpn
4    ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:openvpn
5    ACCEPT     udp  --  anywhere             anywhere             udp dpt:openvpn

Chain FORWARD (policy ACCEPT)
num  target     prot opt source               destination         
1    ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
2    ACCEPT     all  --  10.8.0.0/24          anywhere            

Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         

With this I was able to browse the net again through openvpn.

**Comment by dschaper** [comment]
> Chain INPUT (policy ACCEPT)

That basically turns off the firewall. You have no DROP rules so nothing is being filtered out.

**Comment by dschaper** [comment]
> Chain INPUT (policy DROP)
> num target prot opt source destination
> 1 ACCEPT all -- anywhere anywhere

That doesn't do anything either, The policy is DROP but the first rule accepts anything from anywhere.

Note: Neither of the examples are anything close to what we have in the documentations.

**Comment by dschaper** [comment]
You aren't using our guides, there's no port 53 or 80 or 1194 so I'll close this out.

If you use the ruleset we provide and you still have issues then please continue to comment.

**Comment by dschaper** [comment]
https://www.howtogeek.com/177621/the-beginners-guide-to-iptables-the-linux-firewall/

**Comment by salamdamai** [comment]
Thank you. I understand it better now on how to use itables. 

This is still about the documentation, I hope I dont take away your time much, 

https://docs.pi-hole.net/guides/vpn/installation/

#############################################################################
Welcome to this quick OpenVPN "road warrior" installer

I need to ask you a few questions before starting the setup
You can leave the default options and just press enter if you are ok with them

First I need to know the IPv4 address of the network interface you want OpenVPN
listening to.
IP address: 10.8.0.1
#############################################################################

Is the last part correct? When I run the "road warrior" script, it asks for the IPv4. I was only given the option to enter the external IP address of my cloud server. It wont let me to enter "10.8.0.1". If I am not mistaken, you specify this IPv4 during the PiHole installation.

**Comment by dschaper** [comment]
@RamSet

**Comment by RamSet** [comment]
That IP is the internal IP of the VPN server. It’s ok to use the default 10.8.0.1 ad this will only be used locally by the VPN server and connected clients. 

You will be asked about you external IP/hostname later in the process.

**Comment by RamSet** [comment]
The 10.8.0.1 is default (built in) the install script. You would need to put in the IP assigned to the interface that is open to the internet in your case (public IP if droplet).

The OpenVPN server will use 10.8.0.1/24 for the server and connected clients. 

You should use your public ip there.

**Comment by salamdamai** [comment]
Thank you. 

I feel like the manual is still wrong. 

The manual in: https://docs.pi-hole.net/guides/vpn/installation/ should have been:
BEFORE:
############################################################################
Welcome to this quick OpenVPN "road warrior" installer

I need to ask you a few questions before starting the setup
You can leave the default options and just press enter if you are ok with them

First I need to know the IPv4 address of the network interface you want OpenVPN
listening to.
IP address: 10.8.0.1
##############################################################################

AFTER
############################################################################
Welcome to this quick OpenVPN "road warrior" installer

I need to ask you a few questions before starting the setup
You can leave the default options and just press enter if you are ok with them

First I need to know the IPv4 address of the network interface you want OpenVPN
listening to.
IP address: <public IP address where openvpn server can be accessed>
##############################################################################

If you put 10.8.0.1 in that "IP address:...", it is very confusing for a noob. 

I have figure out the iptables issue that I have been having that you probably can add into the pihole manual.
I was using Debian 10. After applying the iptables to match exactly the output "iptables -L --line-numbers"  shown in:

https://docs.pi-hole.net/guides/vpn/firewall/

I was not able to browse the net. Before applying the iptables, I was able to browse the net and could see the query in pihole web interface changing as I browse the net. It took me many hours to figure this out. It turns out Debian has two iptables running side by side. This messes up a lot of things. The two iptables are:  iptables-nft and iptables-legacy

So before applying the iptables, i enable iptables-nft (disabling iptables-legacy). These two iptables running side by side really mess up all my setup. Without this knowledge, after users apply the iptables described in PIhole firewall manual, they will not be able to browse the net. Even after they execute "iptables -P INPUT ACCEPT", they will not be able to browse the net. They have to disable iptables legacy. 

Anyway, you can close this ticket. 

Thank you for providing the basic information. From there I was able to do more research. Its hard to research something when you do not know what to research. Thus basic information makes a different.
