### ISSUE TITLE
unbound have no uninstall/removal documentation 

### ISSUE THREAD

**Issue by icf20** [pi-hole/docs#553]
According to reddit something like this should be in the documentation 

```
    Stop the service:
    sudo service unbound stop
    Remove unbound package:
    sudo apt remove unbound
    Remove configs and properties:
    sudo rm -r /var/lib/unbound/
    sudo rm -r /etc/unbound/
    Remove dependencies that are not needed anymore:
    sudo apt autoremove
    Clean up:
    sudo apt autoclean
```

**Comment by yubiuser** [comment]
I think stopping the service is not necessary. This PR adds a small note to the guide: https://github.com/pi-hole/docs/pull/555

IMHO, cleaning and autoremove apt cache are beyond the scope of a installation guide of a recursive DNS server.
