### ISSUE TITLE
Add location of regex file to regex docs

### ISSUE THREAD

**Issue by inflatador** [pi-hole/docs#590]
### Versions
N/A
### Platform
N/A
### Actual behavior / bug
[The pi-hole regex extension documentation](https://docs.pi-hole.net/regex/pi-hole/) is filled with a ton of excellent information. However, it doesn't seem to mention which config file you should put your regexes in or how to activate the regex configuration.

### Steps to reproduce

N/A

## Debug Token

N/A

### Screenshots

N/A

### Additional context

If I 'grep -r' the pi-hole source code, it seems the regex file needs to be '${piholeDir}/regex.list' .

Apologies in advance if I missed something. I spent a lot of time reading the tutorial and forums but couldn't find it anywhere else.

**Comment by yubiuser** [comment]
Since v5.0 Pi-hole switched to the `gravity.db`. 
https://docs.pi-hole.net/database/gravity/

`Regex.list` is outdated and should not be used anymore.

You can manually inject regex via SQL or via the web inteface.
