### ISSUE TITLE
Critical typo in WireGuard guide that creates confusion for inexperienced users

### ISSUE THREAD

**Issue by finnblue8** [pi-hole/docs#636]
I believe there is a typo in the WireGuard -> Optional extra features -> Make local devices accessible page in the documentation. I found this whilst following this guide a few weeks ago, and this particular word/phrase will make the steps outlined in this page not work at all unless a user knows how to compare the values of `ip a` with what is written. 

The page in question: https://docs.pi-hole.net/guides/vpn/wireguard/internal/

In the middle of the page the following warning is given:

```

Important: Substitute interface

Without the correct interface name, this will not work!

Substitute eth0 in the preceding lines to match the Internet-facing interface. This may be **ens2p0** or similar on more recent Ubuntu versions (check, e.g., ip a for details about your local interfaces).
```

By all my knowledge "ens2p0" is a misspelling of the proper value "enp2s0."

The phrase is actually spelled correctly further down the page in the example server configuration file given:

```
[Interface]
PrivateKey = [your server's private key]
Address = [Wireguard-internal IPs of the server, e.g. 10.100.0.1/24, fd08:4711::1/64]
ListenPort = 47111

PostUp   = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o **enp2s0** -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o **enp2s0** -j MASQUERADE
```

I run Ubuntu 20.04, and the correct spelling that makes this page work is `enp2s0`. I am fairly certain this is an error, especially given that the server config matches what is on my system. This is a particularly bad typo because users that have little experience with Linux might question whether the correct value for their Ubuntu system is the typo or if it is the correct version in the server config.

**Comment by dschaper** [comment]
Thanks for the post.

I don't see how this can confuse users when they use the interface on their systems? There shouldn't be any copy/pasting of anything.

**Comment by yubiuser** [comment]
Fixed by https://github.com/pi-hole/docs/pull/637
