### ISSUE TITLE
Getting ssl error when accessing the pihole doc

### ISSUE THREAD

**Issue by sunilsankar** [pi-hole/docs#646]
### Versions

- Pi-hole:  
- AdminLTE:  
- FTL:  

### Platform

- OS and version:  

- Platform:  

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug

_A clear and concise description of what the bug is._

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._
![image](https://user-images.githubusercontent.com/2275957/149972928-ac04cd16-0e01-44c0-9717-615c27f139ae.png)

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Thanks for the report, I've updated the CNAME record again but it may take a few minutes to propagate out.

**Comment by sunilsankar** [comment]
It is working now 😃
