### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by rafaelcpalmeida** [pi-hole/docs#666]
### Versions

- Pi-hole:  N/a
- AdminLTE: N/a 
- FTL:  N/a

### Platform

- OS and version:  N/a

- Platform:  N/a

### Expected behavior

Clear and concise documentation regarding setting up the weekly cron schedule.

### Actual behavior / bug

Current documentation is misleading and incomplete.

### Steps to reproduce

1. Go to the [documentation](https://docs.pi-hole.net/guides/dns/cloudflared/?h=cloudflare#automating-cloudflared-updates)

## Debug Token

- URL:  N/a

### Screenshots

<img width="708" alt="image" src="https://user-images.githubusercontent.com/7630784/154528755-115ec798-73b2-4908-a416-93dfae5e9565.png">

### Additional context

When writing the file `/etc/cron.weekly/cloudflared-updater`, a shebang should be added to the top of the file, otherwise, it will fail to execute. This is not clear on documentation. I can happily open a PR to fix this.

**Comment by ImBIOS** [comment]
I have made a PR (#857) to solve this thing, I hope my student would not facing any issue after this.
