### ISSUE TITLE
Cloudflared installation fails with current cloudflared version

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/docs#679]
Our guide (https://docs.pi-hole.net/guides/dns/cloudflared/#automatic-way) recommends the install option `--legacy`. But this flag is not supported anymore in recent `cloudflared` versions.

https://github.com/cloudflare/cloudflared/commit/706523389c83ad3bc9b950bd6cb712864e23f586#diff-b10aaca38c8d89afa4c14ffbc373252118ed207da5216b611e1df2405643af08

The topic was discussed on discourse here: https://discourse.pi-hole.net/t/cloudflared-legacy-service-install-fails/54160

**Comment by sqerk** [comment]
"cloudflared service install --legacy" doesn't work anymore. The "service install" option doesn't work either, without a cloudflare account and domain. But the command "cloudflared proxy-dns" works and can be installed as a service manually
