### ISSUE TITLE
missing download cloudflared-2018.7.2-linux-arm.tar.gz for arm32

### ISSUE THREAD

**Issue by mybuntu-git2** [pi-hole/docs#710]
### Versions
(not relevant)

### Platform
(not relevant)

### Expected behavior
wget  https://bin.equinox.io/a/4SUTAEmvqzB/cloudflared-2018.7.2-linux-arm.tar.gz
will download the required tar and allow install

### Actual behavior / bug
file does not exist 404 error

### Steps to reproduce

wget  https://bin.equinox.io/a/4SUTAEmvqzB/cloudflared-2018.7.2-linux-arm.tar.gz

### Additional context

without this tar it is impossible to install DoH on pi zero w

**Comment by PromoFaux** [comment]
Relates to this guide: https://docs.pi-hole.net/guides/dns/cloudflared/

Assuming related to the workaround note added in https://github.com/pi-hole/docs/pull/475

@pixolin - as the author of that PR, do you have any further recommendations?

**Comment by yubiuser** [comment]
I've found this one: https://hobin.ca/cloudflared/ by looking at the script https://gist.github.com/FrancisTurner/f8d53c40a201bc28328a0e8742d710dc which is linked https://github.com/cloudflare/cloudflared/issues/38#issuecomment-855835095

**Comment by mybuntu-git2** [comment]
> I've found this one: https://hobin.ca/cloudflared/ by looking at the script https://gist.github.com/FrancisTurner/f8d53c40a201bc28328a0e8742d710dc which is linked [cloudflare/cloudflared#38 (comment)](https://github.com/cloudflare/cloudflared/issues/38#issuecomment-855835095)

that seems to stop at Version 2018.8.0 while we need 7.2.

**Comment by mybuntu-git2** [comment]
I tried the latest in that repo, it still gives segmentation fault on my pi zero w.

**Comment by yubiuser** [comment]
Ok, thanks. Unfortunately, we can't do much about it. It's up to `cloudflared` to fix their binaries. All we can offer is to remove the broken link and add a note that `cloudflared` is not working on the mentioned devices.

**Comment by mybuntu-git2** [comment]
indeed I understand that. I will also ask them to recover it and put it into the releases. concerning workarounds: any other way to accomplish doh on a pi zero?

**Comment by mybuntu-git2** [comment]
Cloudflared issue: https://github.com/cloudflare/cloudflared/issues/643

**Comment by yubiuser** [comment]
I can't answer this, I'm not using DoH. Maybe some from the community does know a workaround.

**Comment by yubiuser** [comment]
https://github.com/pi-hole/docs/pull/711 will "fix" the documentation for now, but of course not the underlying issue. If you encounter a workaround let us know and we adjust our documentation

**Comment by reggie88** [comment]
Hi, Internet Archive seem to have a copy of it. 
Going through the steps now on my Pi1B, `cloudflared -v` gives me `cloudflared version 2018.7.2 (built 2018-07-13-1701 UTC)`

https://web.archive.org/web/20201112034736if_/https://bin.equinox.io/a/4SUTAEmvqzB/cloudflared-2018.7.2-linux-arm.tar.gz

Attached the file here aswell, just incase [cloudflared-2018.7.2-linux-arm.tar.gz](https://github.com/pi-hole/docs/files/8773099/cloudflared-2018.7.2-linux-arm.tar.gz)

**Comment by bmidgley** [comment]
@yubiuser there is something about using the latest pi os on a pi zero that results in a system that must be forced to install the 32-bit client. You docs when creating a tunnel for debian 32-bit arm say this:

```
curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm.deb && 

sudo dpkg -i cloudflared.deb && 

sudo cloudflared service install xxx
```

but it doesn't work on a pi zero unless you force the architecture, then it's all good! Weird!

```
curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm.deb && 

sudo dpkg --force-architecture -i cloudflared.deb && 

sudo cloudflared service install xxx
```
