### ISSUE TITLE
Visual error on "Wireguard - Install server" page.

### ISSUE THREAD

**Issue by rdwebdesign** [pi-hole/docs#758]
The sticky footer is not "sticking" to screen bottom.

Error on console:
```
Uncaught ReferenceError: Missing element: expected ".tabbed-labels" to be present
```

### Link
https://docs.pi-hole.net/guides/vpn/wireguard/server/

### Screenshots
![Image Pasted at 2022-8-7 21-40](https://user-images.githubusercontent.com/1385443/183320353-a9fdf39b-13c9-40ee-82c0-2aca6cd0d1f6.png)

**Comment by rdwebdesign** [comment]
I created a quick fix (#759) for this error.
The current visual is almost the same as the original, but without the broken footer.

Note:
Since we have only 2 items, list items are a good/readable option.
If the tabs are really needed, we can find a solution later.

**Comment by rdwebdesign** [comment]
Note2:

Possible solution using tabs is add the `alternate_style` option to the config (not tested):
```
  - pymdownx.tabbed:
      alternate_style: true
```

**Comment by yubiuser** [comment]
Interesting, I get the same console error but no visible bug on Chrome an FF (both on linux)

**Comment by rdwebdesign** [comment]
Did you scroll the page to the bottom?
When I scroll all the way down, the footer scrolls with the text.

![docs758_video](https://user-images.githubusercontent.com/1385443/183486854-6ba85ec3-022c-487d-95c1-03b928162a7f.gif)

**Comment by yubiuser** [comment]
> Did you scroll the page to the bottom?

I did. It stays where it should stay

**Comment by rdwebdesign** [comment]
I tested using Chrome and Edge.
In this case, the footer doesn't scroll up, but the menu is overlapping the footer.

The problem is better visualized using the dark theme.
![image](https://user-images.githubusercontent.com/1385443/183498329-09965081-91d9-4f08-9a58-9ce559317ccb.png)

Anyway, the tabs are not shown as tabs in any browser.

I change my approach and fixed the error. Now the tabs are really tabs.

**Comment by yubiuser** [comment]
![Peek 2022-08-08 21-32](https://user-images.githubusercontent.com/26622301/183499337-398feba5-6e34-4b9a-9fcd-0bbe475a2b8c.gif)

**Comment by rdwebdesign** [comment]
Your screen is large enough to show the menu completely expanded, above the footer.

If you try it using a smaller window (with reduced height), you will probably see the same errors.

**Comment by yubiuser** [comment]
Ok, I can see it now.
