### ISSUE TITLE
DNS cloudflared update script not working

### ISSUE THREAD

**Issue by djalan** [pi-hole/docs#761]
The script in the documentation is incorrect.
https://docs.pi-hole.net/guides/dns/cloudflared/#updating-cloudflared

This is the problem:
> when you already have file 'cloudflared-linux-arm64', wget
> appends a number at the end of the downloaded file and
> the script reinstalls the same old binary

I created the below patch since I am unsure of how to create a pull request.

```
From 042f6a9a31a115f4d774f4f4c4b8c1b67a7d74d3 Mon Sep 17 00:00:00 2001
From: Alain Sirois <alainsirois@gmail.com>
Date: Thu, 11 Aug 2022 02:34:27 -0400
Subject: [PATCH] fix wget not overwriting file by default

when you already have file 'cloudflared-linux-arm64', wget
appends a number at the end of the downloaded file and
the script reinstalls the same old binary
---
 docs/guides/dns/cloudflared.md | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/docs/guides/dns/cloudflared.md b/docs/guides/dns/cloudflared.md
index fa3d6b4..f3ada7d 100644
--- a/docs/guides/dns/cloudflared.md
+++ b/docs/guides/dns/cloudflared.md
@@ -209,9 +209,10 @@ The procedure for updating depends on how you configured the `cloudflared` binar
 If you configured `cloudflared` manually (by writing a systemd unit yourself), to update the binary you'll simply redownload the binary from the same link, and repeat the install procedure.
 
 ```bash
-wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm
+FILE='/tmp/cloudflared-download'
+wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm -O $FILE
 sudo systemctl stop cloudflared
-sudo cp ./cloudflared-linux-arm /usr/local/bin/cloudflared
+sudo cp $FILE /usr/local/bin/cloudflared
 sudo chmod +x /usr/local/bin/cloudflared
 sudo systemctl start cloudflared
 cloudflared -v
-- 
2.37.1
```

**Comment by yubiuser** [comment]
I think the better approach would be to add a removal step to the (old) downloaded file?

**Comment by djalan** [comment]
Both ways are very similar.

The best thing would be to add a timestamp to every download. This way it’s easy to do a rollback with the previous version. I would put it in /var/tmp that is cleaned after 30 days in order to not keep dozens of older versions.

**Comment by yubiuser** [comment]
How about not `cp` but `mv` the files in the first place? No need to temp download something, no need to clean, no duplicated downloads

**Comment by djalan** [comment]
-f      Do not prompt for confirmation before overwriting the destination path.

**Comment by djalan** [comment]
`mv -f` is the winner

`-f      Do not prompt for confirmation before overwriting the destination path.`

Let's not bloat the script with the rollback.
