### ISSUE TITLE
Incorrect flags for pihole-FTL.conf in documenation

### ISSUE THREAD

**Issue by daniluvsuall** [pi-hole/docs#768]
Hello,

Can the documentation in configfile.md please be updated to reflect the correct flags, the documentation says:

REPLY_WHEN_BUSY=DROP|ALLOW|BLOCK|REFUSE (PR https://github.com/pi-hole/FTL/pull/1156 & PR https://github.com/pi-hole/FTL/pull/1341) {#reply_when_busy data-toc-label='Database busy reply'}

When the "ALLOW" flag is incorrect, it should say "ACCEPT" as that is the correct flag that's expected when looking at:

/pi-hole/FTL/blob/master/src/config.c;

Line 694 - https://github.com/pi-hole/FTL/blob/832b8c98c42edcbd9fbfc079c0631acf4cea38ca/src/config.c#L694

I wondered why it never worked when I had it set to what the documentation said.

Thanks

Daniel

**Comment by yubiuser** [comment]
Sorry for the inconvenience you experienced. The documentaion is correct, "Allow" is the correct setting. We changed the source (https://github.com/pi-hole/FTL/pull/1389) to reflect this. However, the code is not in the master branch yet. It will be released with the next Pi-hole update.
