### ISSUE TITLE
Docs for rate limit show incorrect variable to use

### ISSUE THREAD

**Issue by danielhoherd** [pi-hole/docs#790]
As described in this issue https://github.com/pi-hole/docker-pi-hole/issues/1224 the docs show the wrong environment variable to use to configure the query rate limit.

Specifically, this page https://docs.pi-hole.net/ftldns/configfile/#rate_limit makes no mention of prefixing variables with `FTLCONF_`

**Comment by dschaper** [comment]
You need to use the docs for the Docker environment variables. The documentation is correct for `FTL`'s configuration.

**Comment by danielhoherd** [comment]
I'm closing this because it looks like I just misunderstood the docs.
