### ISSUE TITLE
>domain command no longer in FTL but still contained in telnet api page

### ISSUE THREAD

**Issue by burtybob** [pi-hole/docs#913]
### Versions

- Pi-hole:  5.17.1
- AdminLTE:  5.20.1
- FTL:  5.23

### Platform
N/A

### Expected behavior

Run a command from the telnet api page and get a response similar to documented response

### Actual behavior / bug

Running the >domain pi-hole.net example results in unknown command response from FTL

The ">domain pi-hole.net" command is no longer in the ftl code.
It appears to have been removed here: https://github.com/pi-hole/FTL/commit/3a4d8e2 and as far as I can find, hasn't been re-added (my installed version of FTL tells me it's an unknown command)

### Steps to reproduce

1. Go to https://docs.pi-hole.net/ftldns/telnet-api/
2. Follow the "Connect via e.g. telnet 127.0.0.1 4711"
3. Navigate to the "domain" command area of the docs (or direct link: https://docs.pi-hole.net/ftldns/telnet-api/#domain-pi-holenet)
4. Try to run >domain pi-hole.net in the telnet session connected in step 2
5. Receive error "unknown command >domain pi-hole.net"

## Debug Token
N/A
### Screenshots

N/A

### Additional context
It might be worth including some form of "applicable to" in the docs, similar to the way Microsoft have on their MSDN

**Comment by yubiuser** [comment]
Thanks for the detailed analysis. You're spot on. This is a issue with the documentation describing a removed command. I'm just wondering, why it was removed at all (and in this particular commit - which seems a bit unrelated) @DL6ER

**Comment by yubiuser** [comment]
P.S. The whole telnet API will be gone with Pi-hole v6 and replaces by a real REST API.
